"C:\Program Files\Autodesk\Moldflow Insight 2019\bin\runstudy" -temp temp -keeptmp 0LS2.csv.xml.sdy
"C:\Program Files\Autodesk\Moldflow Insight 2019\bin\runstudy" -temp temp -keeptmp 1LS2.csv.xml.sdy
"C:\Program Files\Autodesk\Moldflow Insight 2019\bin\runstudy" -temp temp -keeptmp 2LS2.csv.xml.sdy
"C:\Program Files\Autodesk\Moldflow Insight 2019\bin\runstudy" -temp temp -keeptmp 3LS2.csv.xml.sdy
"C:\Program Files\Autodesk\Moldflow Insight 2019\bin\runstudy" -temp temp -keeptmp 4LS2.csv.xml.sdy
"C:\Program Files\Autodesk\Moldflow Insight 2019\bin\runstudy" -temp temp -keeptmp 5LS2.csv.xml.sdy
"C:\Program Files\Autodesk\Moldflow Insight 2019\bin\runstudy" -temp temp -keeptmp 6LS2.csv.xml.sdy
"C:\Program Files\Autodesk\Moldflow Insight 2019\bin\runstudy" -temp temp -keeptmp 7LS2.csv.xml.sdy
"C:\Program Files\Autodesk\Moldflow Insight 2019\bin\runstudy" -temp temp -keeptmp 8LS2.csv.xml.sdy
"C:\Program Files\Autodesk\Moldflow Insight 2019\bin\runstudy" -temp temp -keeptmp 9LS2.csv.xml.sdy
"C:\Program Files\Autodesk\Moldflow Insight 2019\bin\runstudy" -temp temp -keeptmp 10LS2.csv.xml.sdy
"C:\Program Files\Autodesk\Moldflow Insight 2019\bin\runstudy" -temp temp -keeptmp 11LS2.csv.xml.sdy
"C:\Program Files\Autodesk\Moldflow Insight 2019\bin\runstudy" -temp temp -keeptmp 12LS2.csv.xml.sdy
"C:\Program Files\Autodesk\Moldflow Insight 2019\bin\runstudy" -temp temp -keeptmp 13LS2.csv.xml.sdy
"C:\Program Files\Autodesk\Moldflow Insight 2019\bin\runstudy" -temp temp -keeptmp 14LS2.csv.xml.sdy
"C:\Program Files\Autodesk\Moldflow Insight 2019\bin\runstudy" -temp temp -keeptmp 15LS2.csv.xml.sdy
"C:\Program Files\Autodesk\Moldflow Insight 2019\bin\runstudy" -temp temp -keeptmp 16LS2.csv.xml.sdy
"C:\Program Files\Autodesk\Moldflow Insight 2019\bin\runstudy" -temp temp -keeptmp 17LS2.csv.xml.sdy
"C:\Program Files\Autodesk\Moldflow Insight 2019\bin\runstudy" -temp temp -keeptmp 18LS2.csv.xml.sdy
"C:\Program Files\Autodesk\Moldflow Insight 2019\bin\runstudy" -temp temp -keeptmp 19LS2.csv.xml.sdy
"C:\Program Files\Autodesk\Moldflow Insight 2019\bin\runstudy" -temp temp -keeptmp 20LS2.csv.xml.sdy
"C:\Program Files\Autodesk\Moldflow Insight 2019\bin\runstudy" -temp temp -keeptmp 21LS2.csv.xml.sdy
"C:\Program Files\Autodesk\Moldflow Insight 2019\bin\runstudy" -temp temp -keeptmp 22LS2.csv.xml.sdy
"C:\Program Files\Autodesk\Moldflow Insight 2019\bin\runstudy" -temp temp -keeptmp 23LS2.csv.xml.sdy
"C:\Program Files\Autodesk\Moldflow Insight 2019\bin\runstudy" -temp temp -keeptmp 24LS2.csv.xml.sdy
